# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(choices=[('rock', 'Rock'), ('alt_rock', 'Alternative Rock'), ('psyche_rock', 'Psychedelic Rock'), ('inde_rock', 'Independent Rock'), ('folk_rock', 'Folk Rock'), ('hard_rock', 'Hard Rock'), ('jazz_rock', 'Jazz Rock'), ('opera_rock', 'Opera Rock'), ('classic_rock', 'Classic Rock'), ('blues_rock', 'Blues Rock'), ('elvis', "Elvis'"), ('pop_rock', 'Pop Rock'), ('beatles', "The Beatles'")], max_length=100)),
            ],
            options={
                'ordering': ('artist', 'year'),
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('order', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Album')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together=set([('album_name', 'artist', 'year')]),
        ),
    ]
