# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 14:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-6000), django.core.validators.MaxValueValidator(3000)]),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
