# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160422_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='plays',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='api.Album'),
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set([('album', 'order')]),
        ),
    ]
