# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 16:25
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(-6000), django.core.validators.MaxValueValidator(3000)])),
                ('genre', models.CharField(choices=[('rock', 'Rock'), ('alt_rock', 'Alternative Rock'), ('psyche_rock', 'Psychedelic Rock'), ('inde_rock', 'Independent Rock'), ('folk_rock', 'Folk Rock'), ('hard_rock', 'Hard Rock'), ('jazz_rock', 'Jazz Rock'), ('opera_rock', 'Opera Rock'), ('classic_rock', 'Classic Rock'), ('blues_rock', 'Blues Rock'), ('elvis', "Elvis'"), ('pop_rock', 'Pop Rock'), ('beatles', "The Beatles'")], max_length=100)),
            ],
            options={
                'ordering': ('artist', 'year'),
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.IntegerField()),
                ('plays', models.PositiveIntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='example.Album')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(regex='[0-9+\\-()]*')])),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together=set([('album_name', 'artist', 'year')]),
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set([('album', 'order')]),
        ),
    ]
